/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algoBot;
import algoBot.helper.resourceReader.YamlReader;
import algoBot.slack.BotSecretDto;
import algoBot.timer.Scheduler;
import org.yaml.snakeyaml.Yaml;

import java.io.File;
import java.io.InputStream;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        new Scheduler().schedule();
    }
}
